const mockEvents = {
  city: {
    id: 1007700,
    city: 'München',
    lat: 48.14,
    lon: 11.58,
    state: '',
    country: 'de',
    zip: 'meetup3',
    member_count: 1257,
  },
  events: [
    {
      created: 1573833508000,
      duration: 705600000,
      id: '266491810',
      name: 'The New Man – Das Männerabenteuer [Iron John]',
      rsvp_limit: 12,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1599300000000,
      local_date: '2020-09-05',
      local_time: '12:00',
      updated: 1573833508000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 4,
      is_online_event: false,
      group: {
        created: 1440924660000,
        name: 'No More Mr. Nice Guy Männergruppe München',
        id: 18881708,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'No-More-Mr-Nice-Guy-Muenchen',
        who: 'Männer',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link:
        'https://www.meetup.com/No-More-Mr-Nice-Guy-Muenchen/events/266491810/',
      description:
        '<p>Das Beste ist ein Tagesticket zu kaufen für die Zonen M-3 (10,60.-Euro).<br/>Wir machen eine sommerliche Wanderung entlang der Isar mit Picknik unterwegs. Bitte bringt eueren eigenen Imbiss und das passende<br/>Getränk mit. Wir brauchen bequeme Schuhe da die Wanderung ca.2-3 Stunden dauert.<br/>Wir treffen uns am Hauptbahnhof (Eingang Arnulfstraße)und fahren mit der S-Bahn (S-7) nach Schäftlarn. Dann wandern wir hinunter zur Isar zum Kloster<br/>Schäftlarn (kurzer Stopp beim wunderschönen Klostergarten) weiter den Fluß entlang bis zur Au-Mühle (wer mag kann sich bei der besten Fischzucht der Gegend etwas kaufen (dafür möglichst eine eigene Semmel mitbringen).<br/>Wir suchen uns einen schönen Platz für die Brotzeit,dann gehts weiter Richtung Ickinger Stausee. Wer Lust hat springt hinein oder<br/>kühlt wenigstens die Füße. Zum Schluß gehts wieder bergauf nach Icking und zurück nach München.</p> <p>- Veranstaltungsbeitrag 4,00.-Euro bitte vorab an [masked] bei pay-pal überweisen</p> <p>The best thing is to buy a day ticket for the zones M-3 (10,60.-Euro).<br/>We go for a summer hike along the Isar with picnic on the way. Please bring your own snack and the appropriate<br/>Drink with. We need comfortable shoes as the hike takes about 2-3 hours.<br/>We meet at the main station (entrance Arnulfstraße) and take the S-Bahn (S-7) to Schäftlarn. Then we hike down to the Isar river to the monastery<br/>Schäftlarn (short stop at the beautiful monastery garden) further along the river to the Au-Mühle (if you like you can buy something at the best fish farm in the area (if possible bring your own bread roll)<br/>We will find a nice place for a snack, then we continue towards the Ickinger Stausee. Who feels like jumping in or<br/>at least cool your feet. At the end of the day we go back uphill to Icking and back to Munich.</p> <p>- Please transfer the event fee of 4,00. euro in advance to [masked]</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1580296762000,
      duration: 7200000,
      id: 'tsjmnrybckbdc',
      name: 'Restaurant hopping',
      rsvp_limit: 20,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1595437200000,
      local_date: '2020-07-22',
      local_time: '19:00',
      updated: 1580296762000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 9,
      is_online_event: false,
      group: {
        created: 1578072802000,
        name: 'Foodtour - Foodies are welcome to hop through restaurants',
        id: 33160683,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Foodtour-Foodies-are-welcome-to-hop-through-restaurants',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link:
        'https://www.meetup.com/Foodtour-Foodies-are-welcome-to-hop-through-restaurants/events/tsjmnrybckbdc/',
      description:
        '<p>If you cannot attend, please opt out so others get a chance to meetup.</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1581832065000,
      duration: 3600000,
      id: 'frsfprybckbkb',
      name: "Let's learn the meaning of life in Buddhism",
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1594119600000,
      local_date: '2020-07-07',
      local_time: '13:00',
      updated: 1581832066000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      is_online_event: false,
      group: {
        created: 1449538782000,
        name: 'München Meanings of Life in Buddhism Meetup',
        id: 19192295,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munchen-Meanings-of-Life-in-Buddhism-Meetup',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link:
        'https://www.meetup.com/Munchen-Meanings-of-Life-in-Buddhism-Meetup/events/frsfprybckbkb/',
      description:
        '<p>Das Beste ist ein Tagesticket zu kaufen für die Zonen M-3 (10,60.-Euro).<br/>Wir machen eine sommerliche Wanderung entlang der Isar mit Picknik unterwegs. Bitte bringt eueren eigenen Imbiss und das passende<br/>Getränk mit. Wir brauchen bequeme Schuhe da die Wanderung ca.2-3 Stunden dauert.<br/>Wir treffen uns am Hauptbahnhof (Eingang Arnulfstraße)und fahren mit der S-Bahn (S-7) nach Schäftlarn. Dann wandern wir hinunter zur Isar zum Kloster<br/>Schäftlarn (kurzer Stopp beim wunderschönen Klostergarten) weiter den Fluß entlang bis zur Au-Mühle (wer mag kann sich bei der besten Fischzucht der Gegend etwas kaufen (dafür möglichst eine eigene Semmel mitbringen).<br/>Wir suchen uns einen schönen Platz für die Brotzeit,dann gehts weiter Richtung Ickinger Stausee. Wer Lust hat springt hinein oder<br/>kühlt wenigstens die Füße. Zum Schluß gehts wieder bergauf nach Icking und zurück nach München.</p> <p>- Veranstaltungsbeitrag 4,00.-Euro bitte vorab an [masked] bei pay-pal überweisen</p> <p>The best thing is to buy a day ticket for the zones M-3 (10,60.-Euro).<br/>We go for a summer hike along the Isar with picnic on the way. Please bring your own snack and the appropriate<br/>Drink with. We need comfortable shoes as the hike takes about 2-3 hours.<br/>We meet at the main station (entrance Arnulfstraße) and take the S-Bahn (S-7) to Schäftlarn. Then we hike down to the Isar river to the monastery<br/>Schäftlarn (short stop at the beautiful monastery garden) further along the river to the Au-Mühle (if you like you can buy something at the best fish farm in the area (if possible bring your own bread roll)<br/>We will find a nice place for a snack, then we continue towards the Ickinger Stausee. Who feels like jumping in or<br/>at least cool your feet. At the end of the day we go back uphill to Icking and back to Munich.</p> <p>- Please transfer the event fee of 4,00. euro in advance to [masked]</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1580731483000,
      duration: 3600000,
      fee: {
        accepts: 'cash',
        amount: 16,
        currency: 'EUR',
        description: '',
        label: 'Price',
        required: false,
      },
      id: '268420731',
      name:
        'Mit Tönen verwöhnen für Eltern und Babys im ersten Lebensjahr Neuhausen',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1594042200000,
      local_date: '2020-07-06',
      local_time: '15:30',
      updated: 1580731483000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      venue: {
        id: 26842414,
        name: 'Das kleine Paradies',
        lat: 48.15110397338867,
        lon: 11.536011695861816,
        repinned: true,
        address_1: 'Blutenburgstraße 79',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      is_online_event: false,
      group: {
        created: 1577122409000,
        name: 'Herzensgesang München Meetup Gruppe',
        id: 33129270,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Herzensgesang-Munchen-Meetup-Gruppe',
        who: 'Singbegeisterte',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link:
        'https://www.meetup.com/Herzensgesang-Munchen-Meetup-Gruppe/events/268420731/',
      description:
        '<p>Mit Liedern kannst Du den Alltag mit Baby gestalten und mit Ritualen bereichern. Die Einfachheit der Lieder macht sie im Alltag schnell abrufbar. Für Eltern und Babys bis 1,5 Jahre</p> <p>Montag nachmittag außerhalb der Ferien ab[masked], 15:30-16:30 Uhr</p> <p>Termine Kurs I : 02./09./16./23./30.03., 20./27.04.,[masked] (8x)</p> <p>Kosten 128 Euro</p> <p>Termine Kurs II: 18./25.05., 15./22./29.06., 06./13.07. 2020 (7x)</p> <p>Kosten 112 Euro</p> <p>Ort: Das kleine Paradies, Blutenburgstr. 79, 80634 München<br/>Infos: www.das-kleineparadies.de<br/>Anmeldung: [masked],[masked] (SMS, whatsapp)</p> <p>Du wolltest immer schon neue Lieder lernen, möchtest gerne wieder Anschluss an die Kinderlieder von früher bekommen und eine entspannte Zeit mit Deinem Baby verbringen?</p> <p>Dann bist Du in diesem Singtreffen goldrichtig.</p> <p>Wir singen alte und neue Kinderlieder aus aller Welt, Lieder des Herzens, Chants und einfache Songs aus verschiedenen Kulturen, machen Kniereiter- und Fingerspiele. Der gemeinsame Austausch sowie Entspannungs- und Lockerungsübungen finden in jeder Stunde statt, wir tanzen und ein Abschlusslied rundet den Kurs ab.</p> <p>In diesem Kurs lernst Du, wie Du mit Liedern den Alltag mit Baby gestalten und mit Ritualen bereichern kannst, sodass er zu einer spannenden Familienreise wird.</p> <p>Das Singen von einfachen Chants aus aller Welt erhöht den Pegel der Glückshormone und kann in Stress-Situationen sehr ausgleichend wirken. Die Entspannung, die Du durch das Singen erfährst, überträgt sich auf Dein Baby!</p> <p>Die Lieder sind bewusst einfach gehalten, damit sie im Alltag auch wieder abrufbar sind.</p> <p>Bitte mitbringen: Babydecke, evtl. Tragetuch o.ä. Tragehilfe zum Tanzen, Neugierde und bequeme Kleidung, Perfektionsansprüche an sich selbst dürfen zuhause bleiben oder spätestens an der Garderobe abgegeben werden.Zwinkernd</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1592159853000,
      duration: 7200000,
      id: '271294734',
      name: 'The Importance of Being Earnest - Oscar Wilde',
      rsvp_limit: 12,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1594746000000,
      local_date: '2020-07-14',
      local_time: '19:00',
      updated: 1592159853000,
      utc_offset: 7200000,
      waitlist_count: 8,
      yes_rsvp_count: 12,
      is_online_event: false,
      group: {
        created: 1520326534000,
        name: 'The Classic-Novels-You-Should-Have-Read-Already Bookclub',
        id: 27741411,
        join_mode: 'approval',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Classic-Literature-for-the-Dramatically-Stunted',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link:
        'https://www.meetup.com/Classic-Literature-for-the-Dramatically-Stunted/events/271294734/',
      description:
        '<p>Das Beste ist ein Tagesticket zu kaufen für die Zonen M-3 (10,60.-Euro).<br/>Wir machen eine sommerliche Wanderung entlang der Isar mit Picknik unterwegs. Bitte bringt eueren eigenen Imbiss und das passende<br/>Getränk mit. Wir brauchen bequeme Schuhe da die Wanderung ca.2-3 Stunden dauert.<br/>Wir treffen uns am Hauptbahnhof (Eingang Arnulfstraße)und fahren mit der S-Bahn (S-7) nach Schäftlarn. Dann wandern wir hinunter zur Isar zum Kloster<br/>Schäftlarn (kurzer Stopp beim wunderschönen Klostergarten) weiter den Fluß entlang bis zur Au-Mühle (wer mag kann sich bei der besten Fischzucht der Gegend etwas kaufen (dafür möglichst eine eigene Semmel mitbringen).<br/>Wir suchen uns einen schönen Platz für die Brotzeit,dann gehts weiter Richtung Ickinger Stausee. Wer Lust hat springt hinein oder<br/>kühlt wenigstens die Füße. Zum Schluß gehts wieder bergauf nach Icking und zurück nach München.</p> <p>- Veranstaltungsbeitrag 4,00.-Euro bitte vorab an [masked] bei pay-pal überweisen</p> <p>The best thing is to buy a day ticket for the zones M-3 (10,60.-Euro).<br/>We go for a summer hike along the Isar with picnic on the way. Please bring your own snack and the appropriate<br/>Drink with. We need comfortable shoes as the hike takes about 2-3 hours.<br/>We meet at the main station (entrance Arnulfstraße) and take the S-Bahn (S-7) to Schäftlarn. Then we hike down to the Isar river to the monastery<br/>Schäftlarn (short stop at the beautiful monastery garden) further along the river to the Au-Mühle (if you like you can buy something at the best fish farm in the area (if possible bring your own bread roll)<br/>We will find a nice place for a snack, then we continue towards the Ickinger Stausee. Who feels like jumping in or<br/>at least cool your feet. At the end of the day we go back uphill to Icking and back to Munich.</p> <p>- Please transfer the event fee of 4,00. euro in advance to [masked]</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1588705075000,
      duration: 5400000,
      id: 'bnjbsrybckbkb',
      name: 'Chinese/ German Club in Munich',
      rsvp_limit: 13,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1594141200000,
      local_date: '2020-07-07',
      local_time: '19:00',
      updated: 1592771941000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      venue: {
        id: 26903444,
        name: 'Online',
        lat: 48.13512420654297,
        lon: 11.58198070526123,
        repinned: true,
        address_1: 'Online Adresse noch nicht verfügbar',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      is_online_event: false,
      group: {
        created: 1444592791000,
        name: 'Toastmasters Clubs in and around Munich',
        id: 19017360,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Toastmasters-Clubs-in-and-around-Munich',
        who: 'Toastmaster',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link:
        'https://www.meetup.com/Toastmasters-Clubs-in-and-around-Munich/events/bnjbsrybckbkb/',
      description:
        '<p>Das Beste ist ein Tagesticket zu kaufen für die Zonen M-3 (10,60.-Euro).<br/>Wir machen eine sommerliche Wanderung entlang der Isar mit Picknik unterwegs. Bitte bringt eueren eigenen Imbiss und das passende<br/>Getränk mit. Wir brauchen bequeme Schuhe da die Wanderung ca.2-3 Stunden dauert.<br/>Wir treffen uns am Hauptbahnhof (Eingang Arnulfstraße)und fahren mit der S-Bahn (S-7) nach Schäftlarn. Dann wandern wir hinunter zur Isar zum Kloster<br/>Schäftlarn (kurzer Stopp beim wunderschönen Klostergarten) weiter den Fluß entlang bis zur Au-Mühle (wer mag kann sich bei der besten Fischzucht der Gegend etwas kaufen (dafür möglichst eine eigene Semmel mitbringen).<br/>Wir suchen uns einen schönen Platz für die Brotzeit,dann gehts weiter Richtung Ickinger Stausee. Wer Lust hat springt hinein oder<br/>kühlt wenigstens die Füße. Zum Schluß gehts wieder bergauf nach Icking und zurück nach München.</p> <p>- Veranstaltungsbeitrag 4,00.-Euro bitte vorab an [masked] bei pay-pal überweisen</p> <p>The best thing is to buy a day ticket for the zones M-3 (10,60.-Euro).<br/>We go for a summer hike along the Isar with picnic on the way. Please bring your own snack and the appropriate<br/>Drink with. We need comfortable shoes as the hike takes about 2-3 hours.<br/>We meet at the main station (entrance Arnulfstraße) and take the S-Bahn (S-7) to Schäftlarn. Then we hike down to the Isar river to the monastery<br/>Schäftlarn (short stop at the beautiful monastery garden) further along the river to the Au-Mühle (if you like you can buy something at the best fish farm in the area (if possible bring your own bread roll)<br/>We will find a nice place for a snack, then we continue towards the Ickinger Stausee. Who feels like jumping in or<br/>at least cool your feet. At the end of the day we go back uphill to Icking and back to Munich.</p> <p>- Please transfer the event fee of 4,00. euro in advance to [masked]</p> ',
      how_to_find_us: 'PM Hongnan to get an invite',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1592332381000,
      duration: 3600000,
      id: 'lxfwtrybckbfb',
      name:
        '+Free Meditation & Yoga - CENTER RE-OPENED!  just show up – we start at 19:30h',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1593797400000,
      local_date: '2020-07-03',
      local_time: '19:30',
      updated: 1593547541000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 10,
      venue: {
        id: 26353279,
        name: 'Sahaja Yoga Zentrum München',
        lat: 48.13127899169922,
        lon: 11.589085578918457,
        repinned: true,
        address_1: 'Am Lilienberg 2a',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      is_online_event: false,
      group: {
        created: 1405527637000,
        name: 'Free Meditation & Yoga – in Munich / München',
        id: 15760412,
        join_mode: 'approval',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Free-Meditation-Yoga-Munich',
        who: 'Meditators',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link:
        'https://www.meetup.com/Free-Meditation-Yoga-Munich/events/lxfwtrybckbfb/',
      description:
        '<p>Das Beste ist ein Tagesticket zu kaufen für die Zonen M-3 (10,60.-Euro).<br/>Wir machen eine sommerliche Wanderung entlang der Isar mit Picknik unterwegs. Bitte bringt eueren eigenen Imbiss und das passende<br/>Getränk mit. Wir brauchen bequeme Schuhe da die Wanderung ca.2-3 Stunden dauert.<br/>Wir treffen uns am Hauptbahnhof (Eingang Arnulfstraße)und fahren mit der S-Bahn (S-7) nach Schäftlarn. Dann wandern wir hinunter zur Isar zum Kloster<br/>Schäftlarn (kurzer Stopp beim wunderschönen Klostergarten) weiter den Fluß entlang bis zur Au-Mühle (wer mag kann sich bei der besten Fischzucht der Gegend etwas kaufen (dafür möglichst eine eigene Semmel mitbringen).<br/>Wir suchen uns einen schönen Platz für die Brotzeit,dann gehts weiter Richtung Ickinger Stausee. Wer Lust hat springt hinein oder<br/>kühlt wenigstens die Füße. Zum Schluß gehts wieder bergauf nach Icking und zurück nach München.</p> <p>- Veranstaltungsbeitrag 4,00.-Euro bitte vorab an [masked] bei pay-pal überweisen</p> <p>The best thing is to buy a day ticket for the zones M-3 (10,60.-Euro).<br/>We go for a summer hike along the Isar with picnic on the way. Please bring your own snack and the appropriate<br/>Drink with. We need comfortable shoes as the hike takes about 2-3 hours.<br/>We meet at the main station (entrance Arnulfstraße) and take the S-Bahn (S-7) to Schäftlarn. Then we hike down to the Isar river to the monastery<br/>Schäftlarn (short stop at the beautiful monastery garden) further along the river to the Au-Mühle (if you like you can buy something at the best fish farm in the area (if possible bring your own bread roll)<br/>We will find a nice place for a snack, then we continue towards the Ickinger Stausee. Who feels like jumping in or<br/>at least cool your feet. At the end of the day we go back uphill to Icking and back to Munich.</p> <p>- Please transfer the event fee of 4,00. euro in advance to [masked]</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1592158899000,
      duration: 7200000,
      id: '271294595',
      name: 'Ulysses (Chps. 9 - 14) - James Joyce',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1596560400000,
      local_date: '2020-08-04',
      local_time: '19:00',
      updated: 1592161844000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 10,
      is_online_event: false,
      group: {
        created: 1520326534000,
        name: 'The Classic-Novels-You-Should-Have-Read-Already Bookclub',
        id: 27741411,
        join_mode: 'approval',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Classic-Literature-for-the-Dramatically-Stunted',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link:
        'https://www.meetup.com/Classic-Literature-for-the-Dramatically-Stunted/events/271294595/',
      description:
        '<p>Das Beste ist ein Tagesticket zu kaufen für die Zonen M-3 (10,60.-Euro).<br/>Wir machen eine sommerliche Wanderung entlang der Isar mit Picknik unterwegs. Bitte bringt eueren eigenen Imbiss und das passende<br/>Getränk mit. Wir brauchen bequeme Schuhe da die Wanderung ca.2-3 Stunden dauert.<br/>Wir treffen uns am Hauptbahnhof (Eingang Arnulfstraße)und fahren mit der S-Bahn (S-7) nach Schäftlarn. Dann wandern wir hinunter zur Isar zum Kloster<br/>Schäftlarn (kurzer Stopp beim wunderschönen Klostergarten) weiter den Fluß entlang bis zur Au-Mühle (wer mag kann sich bei der besten Fischzucht der Gegend etwas kaufen (dafür möglichst eine eigene Semmel mitbringen).<br/>Wir suchen uns einen schönen Platz für die Brotzeit,dann gehts weiter Richtung Ickinger Stausee. Wer Lust hat springt hinein oder<br/>kühlt wenigstens die Füße. Zum Schluß gehts wieder bergauf nach Icking und zurück nach München.</p> <p>- Veranstaltungsbeitrag 4,00.-Euro bitte vorab an [masked] bei pay-pal überweisen</p> <p>The best thing is to buy a day ticket for the zones M-3 (10,60.-Euro).<br/>We go for a summer hike along the Isar with picnic on the way. Please bring your own snack and the appropriate<br/>Drink with. We need comfortable shoes as the hike takes about 2-3 hours.<br/>We meet at the main station (entrance Arnulfstraße) and take the S-Bahn (S-7) to Schäftlarn. Then we hike down to the Isar river to the monastery<br/>Schäftlarn (short stop at the beautiful monastery garden) further along the river to the Au-Mühle (if you like you can buy something at the best fish farm in the area (if possible bring your own bread roll)<br/>We will find a nice place for a snack, then we continue towards the Ickinger Stausee. Who feels like jumping in or<br/>at least cool your feet. At the end of the day we go back uphill to Icking and back to Munich.</p> <p>- Please transfer the event fee of 4,00. euro in advance to [masked]</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1592317767000,
      duration: 10800000,
      id: 'gztjtrybckbpb',
      name: 'Come run with the MH3! ',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1594472400000,
      local_date: '2020-07-11',
      local_time: '15:00',
      updated: 1592317767000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 6,
      is_online_event: false,
      group: {
        created: 1436202691000,
        name: 'Munich Hash House Harriers',
        id: 18722783,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munich-Hash-House-Harriers',
        who: 'Hashers and Harriettes',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link:
        'https://www.meetup.com/Munich-Hash-House-Harriers/events/gztjtrybckbpb/',
      description:
        '<p>Das Beste ist ein Tagesticket zu kaufen für die Zonen M-3 (10,60.-Euro).<br/>Wir machen eine sommerliche Wanderung entlang der Isar mit Picknik unterwegs. Bitte bringt eueren eigenen Imbiss und das passende<br/>Getränk mit. Wir brauchen bequeme Schuhe da die Wanderung ca.2-3 Stunden dauert.<br/>Wir treffen uns am Hauptbahnhof (Eingang Arnulfstraße)und fahren mit der S-Bahn (S-7) nach Schäftlarn. Dann wandern wir hinunter zur Isar zum Kloster<br/>Schäftlarn (kurzer Stopp beim wunderschönen Klostergarten) weiter den Fluß entlang bis zur Au-Mühle (wer mag kann sich bei der besten Fischzucht der Gegend etwas kaufen (dafür möglichst eine eigene Semmel mitbringen).<br/>Wir suchen uns einen schönen Platz für die Brotzeit,dann gehts weiter Richtung Ickinger Stausee. Wer Lust hat springt hinein oder<br/>kühlt wenigstens die Füße. Zum Schluß gehts wieder bergauf nach Icking und zurück nach München.</p> <p>- Veranstaltungsbeitrag 4,00.-Euro bitte vorab an [masked] bei pay-pal überweisen</p> <p>The best thing is to buy a day ticket for the zones M-3 (10,60.-Euro).<br/>We go for a summer hike along the Isar with picnic on the way. Please bring your own snack and the appropriate<br/>Drink with. We need comfortable shoes as the hike takes about 2-3 hours.<br/>We meet at the main station (entrance Arnulfstraße) and take the S-Bahn (S-7) to Schäftlarn. Then we hike down to the Isar river to the monastery<br/>Schäftlarn (short stop at the beautiful monastery garden) further along the river to the Au-Mühle (if you like you can buy something at the best fish farm in the area (if possible bring your own bread roll)<br/>We will find a nice place for a snack, then we continue towards the Ickinger Stausee. Who feels like jumping in or<br/>at least cool your feet. At the end of the day we go back uphill to Icking and back to Munich.</p> <p>- Please transfer the event fee of 4,00. euro in advance to [masked]</p> ',
      how_to_find_us: 'To be decided',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1589308091000,
      duration: 10800000,
      id: 'cmxzsrybcjbzb',
      name: 'Friday Beergarden (& pub)',
      rsvp_limit: 40,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1594745100000,
      local_date: '2020-07-14',
      local_time: '18:45',
      updated: 1591796684000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 5,
      venue: {
        id: 26906060,
        name: 'Online event',
        repinned: false,
        country: '',
        localized_country_name: '',
      },
      is_online_event: true,
      group: {
        created: 1210500936000,
        name: 'Munich Stammtisch',
        id: 1145675,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'MunichStammtisch',
        who: 'Munich Stammtischers',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/MunichStammtisch/events/cmxzsrybcjbzb/',
      description:
        "<p>JOIN 30-50 of us for beer, cocktails, food and fun, in beergardens and pubs all round Munich, every Friday of the year! We are only indoors if it's cold or wet.</p> <p>Until it's safe again, we're on video chat each week.<br/>Every Friday Video chat with Jitsi from 7pm. Just click our link to join.</p> ",
      how_to_find_us: 'https://meet.jit.si/FridayBeergarden',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      local_time: '10:00',
      local_date: '2020-07-04',
      link: 'https://www.meetup.com/culture-club-munich/events/271430748/',
      visibility: 'public_limited',
      group: {
        created: 1451573329000,
        name: 'Culture Club Munich',
        id: 19255017,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'culture-club-munich',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      waitlist_count: 8,
      yes_rsvp_count: 9,
      duration: 7200000,
      time: 1593849600000,
      utc_offset: 7200000,
      name: 'Birdwatching Walk in Englischer Garten (2)',
      id: '271430748',
    },
    {
      created: 1592331973000,
      duration: 3600000,
      id: 'bvxjtrybckbdb',
      name: 'offene Meditationsgruppe - München - STARTET WIEDER VORORT',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1593711000000,
      local_date: '2020-07-02',
      local_time: '19:30',
      updated: 1592331973000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 11,
      venue: {
        id: 26353279,
        name: 'Sahaja Yoga Zentrum München',
        lat: 48.13126754760742,
        lon: 11.589075088500977,
        repinned: true,
        address_1: 'Am Lilienberg 2a',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      is_online_event: false,
      group: {
        created: 1405527637000,
        name: 'Free Meditation & Yoga – in Munich / München',
        id: 15760412,
        join_mode: 'approval',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Free-Meditation-Yoga-Munich',
        who: 'Meditators',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link:
        'https://www.meetup.com/Free-Meditation-Yoga-Munich/events/bvxjtrybckbdb/',
      description:
        '<p>STARTET WIEDER VORORT als Präsenz-Meditation!</p> <p>Einstieg ist jederzeit möglich, geeignet für Anfänger und Fortgeschrittene.</p> <p>Grundlagen und Wissen von Sahaja Yoga werden vorgestellt: Wissen über Adi Shakti, Kundalini, Energiezentren, subtile Kanäle in und einfache Reinigungstechniken mit den Elementen, die unterstützend auf unser inneres Wachstum wirken und uns ins Gleichgewicht bringen.</p> <p>Wir lernen wie wir in unserem täglichen Leben in Balance kommen und in einem Zustand der Stille Kraft schöpfen können.</p> <p>Ein zentraler Punkt ist die Stille in uns, die spürbar ist und für jeden, jederzeit zugänglich. Sie ist der Moment im Hier und Jetzt, der uns Inspiration, Freude und vieles mehr schenkt.<br/>In diesem Zustand zu verweilen bedeutet Meditation - und dann ist Platz für inneres Wachstum und Evolution.</p> <p>Jeder Abend beinhaltet auch eine geführte Meditation und auch jederzeit eine Frage-Antwort-Runde.</p> <p>Wir freuen uns auf Euch!</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1593421483000,
      duration: 3600000,
      id: '271598884',
      name: 'Persönliche Weiterentwicklung mit Disziplin Teil 3',
      rsvp_limit: 25,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1593939600000,
      local_date: '2020-07-05',
      local_time: '11:00',
      updated: 1593421506000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 6,
      is_online_event: false,
      group: {
        created: 1579680617000,
        name: 'Persönliche Weiterentwicklung mit Disziplin',
        id: 33230775,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Personliche-Weiterentwicklung-mit-Disziplin',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link:
        'https://www.meetup.com/Personliche-Weiterentwicklung-mit-Disziplin/events/271598884/',
      description:
        '<p>Das Beste ist ein Tagesticket zu kaufen für die Zonen M-3 (10,60.-Euro).<br/>Wir machen eine sommerliche Wanderung entlang der Isar mit Picknik unterwegs. Bitte bringt eueren eigenen Imbiss und das passende<br/>Getränk mit. Wir brauchen bequeme Schuhe da die Wanderung ca.2-3 Stunden dauert.<br/>Wir treffen uns am Hauptbahnhof (Eingang Arnulfstraße)und fahren mit der S-Bahn (S-7) nach Schäftlarn. Dann wandern wir hinunter zur Isar zum Kloster<br/>Schäftlarn (kurzer Stopp beim wunderschönen Klostergarten) weiter den Fluß entlang bis zur Au-Mühle (wer mag kann sich bei der besten Fischzucht der Gegend etwas kaufen (dafür möglichst eine eigene Semmel mitbringen).<br/>Wir suchen uns einen schönen Platz für die Brotzeit,dann gehts weiter Richtung Ickinger Stausee. Wer Lust hat springt hinein oder<br/>kühlt wenigstens die Füße. Zum Schluß gehts wieder bergauf nach Icking und zurück nach München.</p> <p>- Veranstaltungsbeitrag 4,00.-Euro bitte vorab an [masked] bei pay-pal überweisen</p> <p>The best thing is to buy a day ticket for the zones M-3 (10,60.-Euro).<br/>We go for a summer hike along the Isar with picnic on the way. Please bring your own snack and the appropriate<br/>Drink with. We need comfortable shoes as the hike takes about 2-3 hours.<br/>We meet at the main station (entrance Arnulfstraße) and take the S-Bahn (S-7) to Schäftlarn. Then we hike down to the Isar river to the monastery<br/>Schäftlarn (short stop at the beautiful monastery garden) further along the river to the Au-Mühle (if you like you can buy something at the best fish farm in the area (if possible bring your own bread roll)<br/>We will find a nice place for a snack, then we continue towards the Ickinger Stausee. Who feels like jumping in or<br/>at least cool your feet. At the end of the day we go back uphill to Icking and back to Munich.</p> <p>- Please transfer the event fee of 4,00. euro in advance to [masked]</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1580731160000,
      duration: 2700000,
      fee: {
        accepts: 'cash',
        amount: 12,
        currency: 'EUR',
        description: '',
        label: 'Price',
        required: false,
      },
      id: '268420683',
      name:
        'Mit Tönen verwöhnen für Eltern und Kleinkinder von 1,5 bis 3 Jahre Neuhausen',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1594651500000,
      local_date: '2020-07-13',
      local_time: '16:45',
      updated: 1580731160000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      venue: {
        id: 26842414,
        name: 'Das kleine Paradies',
        lat: 48.15110397338867,
        lon: 11.536011695861816,
        repinned: true,
        address_1: 'Blutenburgstraße 79',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      is_online_event: false,
      group: {
        created: 1577122409000,
        name: 'Herzensgesang München Meetup Gruppe',
        id: 33129270,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Herzensgesang-Munchen-Meetup-Gruppe',
        who: 'Singbegeisterte',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link:
        'https://www.meetup.com/Herzensgesang-Munchen-Meetup-Gruppe/events/268420683/',
      description:
        '<p>Mit Liedern kannst Du den Alltag mit Kleinkind gestalten und mit Ritualen bereichern. Die Einfachheit der Lieder macht sie im Alltag schnell abrufbar. Für Eltern und Kinder von 1,5-3 Jahren</p> <p>Termine: Montags jeweils 16:45-17:30 Uhr</p> <p>Ort: Das kleine Paradies, Blutenburgstr. 79, 80634 München</p> <p>Termine Kurs I : 02./09./16./23./30.03., 20./27.04.,[masked] (8x)<br/>Kosten: 96 Euro</p> <p>Termine Kurs II: 18./25.05., 15./22./29.06., 06./13.07. 2020 (7x)<br/>Kosten 84 Euro</p> <p>Infos, Anmeldung: [masked]</p> <p>Du wolltest immer schon neue Lieder lernen, möchtest gerne wieder Anschluss an die Kinderlieder von früher bekommen und eine entspannte Zeit mit Deinem Kind verbringen?</p> <p>Dann bist Du in diesem Kurs goldrichtig.</p> <p>Wir singen alte und neue Kinderlieder aus aller Welt, Lieder des Herzens, Chants und einfache Songs aus verschiedenen Kulturen, machen Kniereiter, Fingerspiele und Tänze.</p> <p>In diesem Kurs lernst Du, wie Du mit Liedern den Alltag mit Kind gestalten und mit Ritualen bereichern kannst, sodass er zu einer spannenden Familienreise wird.</p> <p>Das Singen von einfachen Chants aus aller Welt erhöht den Pegel der Glückshormone und kann in Stress-Situationen sehr ausgleichend wirken.</p> <p>Die Lieder sind bewusst einfach gehalten, damit sie im Alltag auch wieder abrufbar sind.</p> <p>Bitte mitbringen: Babydecke, evtl. Tragetuch o.ä. Tragehilfe zum Tanzen, Neugierde und bequeme Kleidung, Perfektionsansprüche an sich selbst dürfen zuhause bleiben oder spätestens an der Garderobe abgegeben werden.</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1593325107000,
      duration: 3600000,
      id: 'vmhttrybckbhb',
      name: 'The Purpose of Life in Buddhism',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1593932400000,
      local_date: '2020-07-05',
      local_time: '09:00',
      updated: 1593325126000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      is_online_event: false,
      group: {
        created: 1449538782000,
        name: 'München Meanings of Life in Buddhism Meetup',
        id: 19192295,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munchen-Meanings-of-Life-in-Buddhism-Meetup',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link:
        'https://www.meetup.com/Munchen-Meanings-of-Life-in-Buddhism-Meetup/events/vmhttrybckbhb/',
      description:
        '<p>Das Beste ist ein Tagesticket zu kaufen für die Zonen M-3 (10,60.-Euro).<br/>Wir machen eine sommerliche Wanderung entlang der Isar mit Picknik unterwegs. Bitte bringt eueren eigenen Imbiss und das passende<br/>Getränk mit. Wir brauchen bequeme Schuhe da die Wanderung ca.2-3 Stunden dauert.<br/>Wir treffen uns am Hauptbahnhof (Eingang Arnulfstraße)und fahren mit der S-Bahn (S-7) nach Schäftlarn. Dann wandern wir hinunter zur Isar zum Kloster<br/>Schäftlarn (kurzer Stopp beim wunderschönen Klostergarten) weiter den Fluß entlang bis zur Au-Mühle (wer mag kann sich bei der besten Fischzucht der Gegend etwas kaufen (dafür möglichst eine eigene Semmel mitbringen).<br/>Wir suchen uns einen schönen Platz für die Brotzeit,dann gehts weiter Richtung Ickinger Stausee. Wer Lust hat springt hinein oder<br/>kühlt wenigstens die Füße. Zum Schluß gehts wieder bergauf nach Icking und zurück nach München.</p> <p>- Veranstaltungsbeitrag 4,00.-Euro bitte vorab an [masked] bei pay-pal überweisen</p> <p>The best thing is to buy a day ticket for the zones M-3 (10,60.-Euro).<br/>We go for a summer hike along the Isar with picnic on the way. Please bring your own snack and the appropriate<br/>Drink with. We need comfortable shoes as the hike takes about 2-3 hours.<br/>We meet at the main station (entrance Arnulfstraße) and take the S-Bahn (S-7) to Schäftlarn. Then we hike down to the Isar river to the monastery<br/>Schäftlarn (short stop at the beautiful monastery garden) further along the river to the Au-Mühle (if you like you can buy something at the best fish farm in the area (if possible bring your own bread roll)<br/>We will find a nice place for a snack, then we continue towards the Ickinger Stausee. Who feels like jumping in or<br/>at least cool your feet. At the end of the day we go back uphill to Icking and back to Munich.</p> <p>- Please transfer the event fee of 4,00. euro in advance to [masked]</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1592331633000,
      duration: 5400000,
      id: 'zsxjtrybckbjb',
      name:
        'Young Generation - Free Meditation - Sahaja Yoga Center RE-OPENED!',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1594056600000,
      local_date: '2020-07-06',
      local_time: '19:30',
      updated: 1592331633000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 6,
      venue: {
        id: 26353279,
        name: 'Sahaja Yoga Zentrum München',
        lat: 48.13126754760742,
        lon: 11.589075088500977,
        repinned: true,
        address_1: 'Am Lilienberg 2a',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      is_online_event: false,
      group: {
        created: 1405527637000,
        name: 'Free Meditation & Yoga – in Munich / München',
        id: 15760412,
        join_mode: 'approval',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Free-Meditation-Yoga-Munich',
        who: 'Meditators',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link:
        'https://www.meetup.com/Free-Meditation-Yoga-Munich/events/zsxjtrybckbjb/',
      description:
        '<p>Das Beste ist ein Tagesticket zu kaufen für die Zonen M-3 (10,60.-Euro).<br/>Wir machen eine sommerliche Wanderung entlang der Isar mit Picknik unterwegs. Bitte bringt eueren eigenen Imbiss und das passende<br/>Getränk mit. Wir brauchen bequeme Schuhe da die Wanderung ca.2-3 Stunden dauert.<br/>Wir treffen uns am Hauptbahnhof (Eingang Arnulfstraße)und fahren mit der S-Bahn (S-7) nach Schäftlarn. Dann wandern wir hinunter zur Isar zum Kloster<br/>Schäftlarn (kurzer Stopp beim wunderschönen Klostergarten) weiter den Fluß entlang bis zur Au-Mühle (wer mag kann sich bei der besten Fischzucht der Gegend etwas kaufen (dafür möglichst eine eigene Semmel mitbringen).<br/>Wir suchen uns einen schönen Platz für die Brotzeit,dann gehts weiter Richtung Ickinger Stausee. Wer Lust hat springt hinein oder<br/>kühlt wenigstens die Füße. Zum Schluß gehts wieder bergauf nach Icking und zurück nach München.</p> <p>- Veranstaltungsbeitrag 4,00.-Euro bitte vorab an [masked] bei pay-pal überweisen</p> <p>The best thing is to buy a day ticket for the zones M-3 (10,60.-Euro).<br/>We go for a summer hike along the Isar with picnic on the way. Please bring your own snack and the appropriate<br/>Drink with. We need comfortable shoes as the hike takes about 2-3 hours.<br/>We meet at the main station (entrance Arnulfstraße) and take the S-Bahn (S-7) to Schäftlarn. Then we hike down to the Isar river to the monastery<br/>Schäftlarn (short stop at the beautiful monastery garden) further along the river to the Au-Mühle (if you like you can buy something at the best fish farm in the area (if possible bring your own bread roll)<br/>We will find a nice place for a snack, then we continue towards the Ickinger Stausee. Who feels like jumping in or<br/>at least cool your feet. At the end of the day we go back uphill to Icking and back to Munich.</p> <p>- Please transfer the event fee of 4,00. euro in advance to [masked]</p> ',
      how_to_find_us: 'S-Bahn Rosenheimerplatz, gegenüber Gasteig',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1580673468000,
      duration: 7200000,
      fee: {
        accepts: 'cash',
        amount: 18,
        currency: 'EUR',
        description: '',
        label: 'Price',
        required: false,
      },
      id: '268406760',
      name: 'Mit_Sing_Konzert "Komm heim, meine Seele, singe!"',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1601226000000,
      local_date: '2020-09-27',
      local_time: '19:00',
      updated: 1580673860000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      venue: {
        id: 26022977,
        name: 'FraunbergStudio',
        lat: 48.10029602050781,
        lon: 11.545408248901367,
        repinned: true,
        address_1: 'Fraunbergstraße 3',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      is_online_event: false,
      group: {
        created: 1577122409000,
        name: 'Herzensgesang München Meetup Gruppe',
        id: 33129270,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Herzensgesang-Munchen-Meetup-Gruppe',
        who: 'Singbegeisterte',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link:
        'https://www.meetup.com/Herzensgesang-Munchen-Meetup-Gruppe/events/268406760/',
      description:
        '<p>einfach kommen, dabei sein, lauschen, genießen und singen....</p> <p>Mitsingkonzert mit Seelen- und Herzensliedern<br/>zum Ankommen, Entspannen, sich mit sich verbinden und loslassen.</p> <p>Komm, wie Du bist!</p> <p>Eintritt je nach Selbsteinschätzung: empfohlen € 18.- bis 25.-</p> <p>Music gives a soul to the universe, wings to the mind, flight to imagination and life to everything. (Plato)</p> <p>Verbinde Dich hier und jetzt mit Deiner Seele, mit Deiner Stimme, mit Deiner Herzensgabe, Deiner Liebe zum Leben, Deiner Liebe zur Erde und der Ernte, die Du in diesem Herbst einfahren darfst.</p> <p>SEI EINFACH DA!</p> <p>Nika hat nicht nur eine tolle Stimme, die mitreißt. Sie IST eine kraftvolle Stimme in Zeiten des Wandels. Eine, die „JA“ sagt zum Leben mit allem, was ist.<br/>Eine, deren Lieder wie gute Freunde sind, die uns unterstützen, nachdenklich machen und unsere Lebensfreude herauskitzeln.</p> <p>Nika teilt mit uns deutschsprachige Herzensmusik aus eigener Feder sowie Rainbow-Songs und Chants aus verschiedenen Kulturen.<br/>Es wird eine musikalische Reise zum Einschwingen und Mitsingen oder auch Lauschen und Träumen. Nikas Stimme rangiert von zart und verletzlich über erotisch und ehrlich bis hin zu frech und kraftvoll... Ein purer Genuss für Herz und Sinne.</p> <p>Wir freuen uns auf Dich und uns!</p> <p>www.herzensgesang.de</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1580226850000,
      duration: 7200000,
      id: '268267658',
      name: 'Video & Film Makers - Social',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1600362000000,
      local_date: '2020-09-17',
      local_time: '19:00',
      updated: 1592151596000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 47,
      venue: {
        id: 26465734,
        name: 'Hofbräukeller',
        lat: 48.13409423828125,
        lon: 11.595478057861328,
        repinned: true,
        address_1: 'Innere Wiener Straße 19',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      is_online_event: false,
      group: {
        created: 1414170061000,
        name: 'Munich Film & Video Making',
        id: 17837322,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'MunichFilmMaking',
        who: 'Filmmakers',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/MunichFilmMaking/events/268267658/',
      description:
        '<p>//// DATE CHANGED ---&gt; 17th September///////<br/>The social gathering is pushed back in order to help the confinement of the coronavirus.</p> <p>Dear Video enthusiasts,</p> <p>Videos are booming!</p> <p>Branding, animations, educational, documentaries, tutorials, interviews, vlogs and many more video formats are getting accessible to everyone, not only on the consumption side, but also on the making!</p> <p>Do you have it in you to capture moments, tell stories or envision video ideas?</p> <p>This is the occasion to meet, learn and collaborate with videobuilders!</p> <p>This is a purely social event for networking. At first, we start by a round of table to get to know everybody and what they are interested with, and then we end up getting chitty chatty all over the place :)</p> <p>See yall there.</p> <p>• What to bring</p> <p>• Important to know</p> ',
      how_to_find_us: 'There will be a table reserved at the name Arty.',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1593325107000,
      duration: 3600000,
      id: 'vmhttrybckbzb',
      name: 'The Purpose of Life in Buddhism',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1595145600000,
      local_date: '2020-07-19',
      local_time: '10:00',
      updated: 1593325356000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      is_online_event: false,
      group: {
        created: 1449538782000,
        name: 'München Meanings of Life in Buddhism Meetup',
        id: 19192295,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munchen-Meanings-of-Life-in-Buddhism-Meetup',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link:
        'https://www.meetup.com/Munchen-Meanings-of-Life-in-Buddhism-Meetup/events/vmhttrybckbzb/',
      description:
        '<p>Das Beste ist ein Tagesticket zu kaufen für die Zonen M-3 (10,60.-Euro).<br/>Wir machen eine sommerliche Wanderung entlang der Isar mit Picknik unterwegs. Bitte bringt eueren eigenen Imbiss und das passende<br/>Getränk mit. Wir brauchen bequeme Schuhe da die Wanderung ca.2-3 Stunden dauert.<br/>Wir treffen uns am Hauptbahnhof (Eingang Arnulfstraße)und fahren mit der S-Bahn (S-7) nach Schäftlarn. Dann wandern wir hinunter zur Isar zum Kloster<br/>Schäftlarn (kurzer Stopp beim wunderschönen Klostergarten) weiter den Fluß entlang bis zur Au-Mühle (wer mag kann sich bei der besten Fischzucht der Gegend etwas kaufen (dafür möglichst eine eigene Semmel mitbringen).<br/>Wir suchen uns einen schönen Platz für die Brotzeit,dann gehts weiter Richtung Ickinger Stausee. Wer Lust hat springt hinein oder<br/>kühlt wenigstens die Füße. Zum Schluß gehts wieder bergauf nach Icking und zurück nach München.</p> <p>- Veranstaltungsbeitrag 4,00.-Euro bitte vorab an [masked] bei pay-pal überweisen</p> <p>The best thing is to buy a day ticket for the zones M-3 (10,60.-Euro).<br/>We go for a summer hike along the Isar with picnic on the way. Please bring your own snack and the appropriate<br/>Drink with. We need comfortable shoes as the hike takes about 2-3 hours.<br/>We meet at the main station (entrance Arnulfstraße) and take the S-Bahn (S-7) to Schäftlarn. Then we hike down to the Isar river to the monastery<br/>Schäftlarn (short stop at the beautiful monastery garden) further along the river to the Au-Mühle (if you like you can buy something at the best fish farm in the area (if possible bring your own bread roll)<br/>We will find a nice place for a snack, then we continue towards the Ickinger Stausee. Who feels like jumping in or<br/>at least cool your feet. At the end of the day we go back uphill to Icking and back to Munich.</p> <p>- Please transfer the event fee of 4,00. euro in advance to [masked]</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1593538227000,
      duration: 19800000,
      fee: {
        accepts: 'paypal',
        amount: 4,
        currency: 'EUR',
        description: '',
        label: 'Price',
        required: true,
      },
      id: '271628335',
      name:
        'Große Isarwanderung von Schäftlarn bis Icking,Great hike on the Isar .',
      rsvp_limit: 19,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1593851400000,
      local_date: '2020-07-04',
      local_time: '10:30',
      updated: 1593545431000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 19,
      venue: {
        id: 24314156,
        name: 'Hauptbahnhof Entrance ',
        lat: 48.14168167114258,
        lon: 11.559309959411621,
        repinned: true,
        address_1: 'Arnulfstraße 4',
        city: 'München ',
        country: 'DE',
        localized_country_name: 'Germany',
      },
      is_online_event: false,
      group: {
        created: 1493907703000,
        name: 'German Conversation Club Munich',
        id: 23587093,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'German-Conversation-Club-Munich',
        who: 'German Clubbers',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link:
        'https://www.meetup.com/German-Conversation-Club-Munich/events/271628335/',
      description:
        '<p>Das Beste ist ein Tagesticket zu kaufen für die Zonen M-3 (10,60.-Euro).<br/>Wir machen eine sommerliche Wanderung entlang der Isar mit Picknik unterwegs. Bitte bringt eueren eigenen Imbiss und das passende<br/>Getränk mit. Wir brauchen bequeme Schuhe da die Wanderung ca.2-3 Stunden dauert.<br/>Wir treffen uns am Hauptbahnhof (Eingang Arnulfstraße)und fahren mit der S-Bahn (S-7) nach Schäftlarn. Dann wandern wir hinunter zur Isar zum Kloster<br/>Schäftlarn (kurzer Stopp beim wunderschönen Klostergarten) weiter den Fluß entlang bis zur Au-Mühle (wer mag kann sich bei der besten Fischzucht der Gegend etwas kaufen (dafür möglichst eine eigene Semmel mitbringen).<br/>Wir suchen uns einen schönen Platz für die Brotzeit,dann gehts weiter Richtung Ickinger Stausee. Wer Lust hat springt hinein oder<br/>kühlt wenigstens die Füße. Zum Schluß gehts wieder bergauf nach Icking und zurück nach München.</p> <p>- Veranstaltungsbeitrag 4,00.-Euro bitte vorab an [masked] bei pay-pal überweisen</p> <p>The best thing is to buy a day ticket for the zones M-3 (10,60.-Euro).<br/>We go for a summer hike along the Isar with picnic on the way. Please bring your own snack and the appropriate<br/>Drink with. We need comfortable shoes as the hike takes about 2-3 hours.<br/>We meet at the main station (entrance Arnulfstraße) and take the S-Bahn (S-7) to Schäftlarn. Then we hike down to the Isar river to the monastery<br/>Schäftlarn (short stop at the beautiful monastery garden) further along the river to the Au-Mühle (if you like you can buy something at the best fish farm in the area (if possible bring your own bread roll)<br/>We will find a nice place for a snack, then we continue towards the Ickinger Stausee. Who feels like jumping in or<br/>at least cool your feet. At the end of the day we go back uphill to Icking and back to Munich.</p> <p>- Please transfer the event fee of 4,00. euro in advance to [masked]</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
  ],
};

let mockEvents_filter = {
  city: {
    id: 1007700,
    city: 'München',
    lat: 48.14,
    lon: 11.58,
    state: '',
    country: 'de',
    zip: 'meetup3',
    member_count: 1257,
  },
  events: [
    {
      created: 1593607298000,
      duration: 7200000,
      id: '271645427',
      name: 'Fashion Talk. Next Round: Diversity in the Fashion Industry ',
      rsvp_limit: 20,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1599318000000,
      local_date: '2020-09-05',
      local_time: '17:00',
      updated: 1593762652000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      is_online_event: false,
      group: {
        created: 1593605746000,
        name: 'Fashion Talk',
        id: 33911163,
        join_mode: 'approval',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Fashion-Talk',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Fashion-Talk/events/271645427/',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1592159853000,
      duration: 7200000,
      id: '271294734',
      name: 'The Importance of Being Earnest - Oscar Wilde',
      rsvp_limit: 12,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1594746000000,
      local_date: '2020-07-14',
      local_time: '19:00',
      updated: 1592159853000,
      utc_offset: 7200000,
      waitlist_count: 11,
      yes_rsvp_count: 12,
      is_online_event: false,
      group: {
        created: 1520326534000,
        name: 'The Classic-Novels-You-Should-Have-Read-Already Bookclub',
        id: 27741411,
        join_mode: 'approval',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Classic-Literature-for-the-Dramatically-Stunted',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link:
        'https://www.meetup.com/Classic-Literature-for-the-Dramatically-Stunted/events/271294734/',
      description:
        '<p>The rapid-fire wit and eccentric characters of The Importance of Being Earnest have make this the perfect classic to follow such a serious tomb as Ulysses. Did I mention it\'s only 76 pages...? ;)</p> <p>At this meetup we\'ll have an open discussion about the book with everyone getting an opportunity to share their thoughts, likes, and dislikes. To keep us on track I come with a list of cheesy (though thought provoking) open questions. Question quality is not guaranteed, only my rambling curiosities.</p> <p>For more information on the book:<br/><a href="https://www.goodreads.com/book/show/92303.The_Importance_of_Being_Earnest" class="linkified">https://www.goodreads.com/book/show/92303.The_Importance_of_Being_Earnest</a></p> <p>Optionally, you can help to cover the cost of the meetup subscription by adding to the piggy bank during the meet up.</p> <p>Hope to see you there!<br/>Bobby</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      local_time: '15:00',
      local_date: '2020-07-26',
      link: 'https://www.meetup.com/Monthly-Creative-Jam/events/pxfbnrybckbzb/',
      visibility: 'public_limited',
      group: {
        created: 1571595318000,
        name: 'Monthly Creative Jam in Munich',
        id: 32916012,
        join_mode: 'approval',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Monthly-Creative-Jam',
        who: 'Jammers',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      waitlist_count: 0,
      yes_rsvp_count: 4,
      duration: 10800000,
      time: 1595768400000,
      utc_offset: 7200000,
      name: 'Monthly Bunker Jam',
      id: 'pxfbnrybckbzb',
    },
    {
      created: 1580226850000,
      duration: 7200000,
      id: '268267658',
      name: 'Video & Film Makers - Social',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1600362000000,
      local_date: '2020-09-17',
      local_time: '19:00',
      updated: 1592151596000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 47,
      venue: {
        id: 26465734,
        name: 'Hofbräukeller',
        lat: 48.13409423828125,
        lon: 11.595478057861328,
        repinned: true,
        address_1: 'Innere Wiener Straße 19',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      is_online_event: false,
      group: {
        created: 1414170061000,
        name: 'Munich Film & Video Making',
        id: 17837322,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'MunichFilmMaking',
        who: 'Filmmakers',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/MunichFilmMaking/events/268267658/',
      description:
        '<p>//// DATE CHANGED ---&gt; 17th September///////<br/>The social gathering is pushed back in order to help the confinement of the coronavirus.</p> <p>Dear Video enthusiasts,</p> <p>Videos are booming!</p> <p>Branding, animations, educational, documentaries, tutorials, interviews, vlogs and many more video formats are getting accessible to everyone, not only on the consumption side, but also on the making!</p> <p>Do you have it in you to capture moments, tell stories or envision video ideas?</p> <p>This is the occasion to meet, learn and collaborate with videobuilders!</p> <p>This is a purely social event for networking. At first, we start by a round of table to get to know everybody and what they are interested with, and then we end up getting chitty chatty all over the place :)</p> <p>See yall there.</p> <p>• What to bring</p> <p>• Important to know</p> ',
      how_to_find_us: 'There will be a table reserved at the name Arty.',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1592158899000,
      duration: 7200000,
      id: '271294595',
      name: 'Ulysses (Chps. 9 - 14) - James Joyce',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1596560400000,
      local_date: '2020-08-04',
      local_time: '19:00',
      updated: 1592161844000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 10,
      is_online_event: false,
      group: {
        created: 1520326534000,
        name: 'The Classic-Novels-You-Should-Have-Read-Already Bookclub',
        id: 27741411,
        join_mode: 'approval',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Classic-Literature-for-the-Dramatically-Stunted',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link:
        'https://www.meetup.com/Classic-Literature-for-the-Dramatically-Stunted/events/271294595/',
      description:
        '<p>"You can\'t eat a whole elephant at once, you need to make small elephant sandwiches" - My old chemistry teacher</p> <p>For the second Ulysses meetup we\'ll be discussing chapters 9 through 14 (~300 pages).</p> <p>At this meetup we\'ll have an open discussion about the book with everyone getting an opportunity to share their thoughts, likes, and dislikes. To keep us on track I come with a list of cheesy (though thought provoking) open questions. Question quality is not guaranteed, only my rambling curiosities.</p> <p>For more information on the book:<br/><a href="https://www.goodreads.com/book/show/338798.Ulysses" class="linkified">https://www.goodreads.com/book/show/338798.Ulysses</a></p> <p>Optionally, you can help to cover the cost of the meetup subscription by adding to the piggy bank during the meet up :)</p> <p>Hope to see you there!<br/>Bobby</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1589308091000,
      duration: 10800000,
      id: 'cmxzsrybcjbzb',
      name: 'Friday Beergarden (& pub)',
      rsvp_limit: 40,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1594745100000,
      local_date: '2020-07-14',
      local_time: '18:45',
      updated: 1591796684000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 7,
      venue: {
        id: 26906060,
        name: 'Online event',
        repinned: false,
        country: '',
        localized_country_name: '',
      },
      is_online_event: true,
      group: {
        created: 1210500936000,
        name: 'Munich Stammtisch',
        id: 1145675,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'MunichStammtisch',
        who: 'Munich Stammtischers',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/MunichStammtisch/events/cmxzsrybcjbzb/',
      description:
        "<p>JOIN 30-50 of us for beer, cocktails, food and fun, in beergardens and pubs all round Munich, every Friday of the year! We are only indoors if it's cold or wet.</p> <p>Until it's safe again, we're on video chat each week.<br/>Every Friday Video chat with Jitsi from 7pm. Just click our link to join.</p> ",
      how_to_find_us: 'https://meet.jit.si/FridayBeergarden',
      visibility: 'public',
      member_pay_fee: false,
    },
  ],
};

export { mockEvents, mockEvents_filter };
